#!/usr/bin/env node
/**
 * Build knowledge/INDEX.md from the front matter of every English knowledge file.
 *
 *   node scripts/build-index.js          # write the index
 *   node scripts/build-index.js --check  # exit 1 if the index is out of date
 */
const fs = require("fs");
const path = require("path");
const { KNOWLEDGE, markdownFiles, parseFrontMatter } = require("./lib");

const enDir = path.join(KNOWLEDGE, "en");
const files = markdownFiles(enDir).sort();

const groups = new Map();
for (const file of files) {
  const rel = path.relative(enDir, file).split(path.sep).join("/");
  const { data } = parseFrontMatter(fs.readFileSync(file, "utf8"));
  if (!data) continue;
  const folder = rel.includes("/") ? rel.split("/")[0] : "";
  if (!groups.has(folder)) groups.set(folder, []);
  const bnPath = path.join(KNOWLEDGE, "bn", rel);
  groups.get(folder).push({ rel, data, hasBn: fs.existsSync(bnPath) });
}

const prettyFolder = (f) =>
  f.replace(/^\d+-/, "").replace(/-/g, " ").replace(/^./, (c) => c.toUpperCase());

let out = "# Knowledge index\n\n";
out +=
  "<!-- Generated by scripts/build-index.js. Do not edit by hand. -->\n\n" +
  "Every file in the knowledge base, with a one-line summary. English files are in `knowledge/en/`. " +
  "Where a Bangla version exists it is at the same path in `knowledge/bn/`.\n\n";

for (const [folder, items] of groups) {
  out += `## ${prettyFolder(folder)}\n\n`;
  out += "| File | Summary | Updated | Bangla |\n|---|---|---|---|\n";
  for (const it of items) {
    const name = it.data.title || it.rel;
    const bn = it.hasBn ? `[bn/${it.rel}](bn/${it.rel})` : "-";
    const summary = String(it.data.summary || "").replace(/\|/g, "\\|");
    out += `| [${name}](en/${it.rel}) | ${summary} | ${it.data.last_updated || ""} | ${bn} |\n`;
  }
  out += "\n";
}

const target = path.join(KNOWLEDGE, "INDEX.md");
if (process.argv.includes("--check")) {
  const current = fs.existsSync(target) ? fs.readFileSync(target, "utf8") : "";
  if (current !== out) {
    console.error("knowledge/INDEX.md is out of date. Run: npm run index");
    process.exit(1);
  }
  console.log("INDEX.md is up to date.");
} else {
  fs.writeFileSync(target, out);
  console.log(`Wrote knowledge/INDEX.md (${files.length} files).`);
}
